baseURL = 'http://cmadsen.tk/'
languageCode = 'da-dk'
title = 'cmadsen'
theme = "xmin" 
pluralizeListTitles = "false"

[[menu.main]]
name = "Hjem"
url = ""
weight = 1

[[menu.main]]
name = "Bodegarute"
url = "bodega/"
weight = 2

[[menu.main]]
name = "Memes"
url = "memes/"
weight = 3

[[menu.main]]
name = "Termer"
url = "termer/"
weight = 4

[[menu.main]]
name = "Kontakt"
url = "kontakt/"
weight = 10